version: '3'

services:
  psql:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - ./storage:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 7s
      timeout: 5s
      retries: 1
          
  kafka:
    image: apache/kafka
    container_name: kafka
    ports:
      - '9092:9092'
      - '29092:29092'   


networks:
  db:
    driver: bridge